#! /bin/bash

if [ -z "$1" ]; then
    echo "You need to pass in a docker tag name"
    exit
fi

# These should be set from `eval "$(docker-machine env default)"`
# DOCKER_HOST=tcp://192.168.99.100:2376
# DOCKER_CERT_PATH=$HOME/.docker/machine/machines/default
# DOCKER_TLS_VERIFY=1

clear
# docker exec -it $1 sh
docker exec -it $1 sh -c "export TERM=xterm-256color; \
export LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33'; \
export LS_OPTS='--color=auto'; \
export PS1='$1:\[\e[33m\]\w\[\e[m\] \u \[\e[36m\]\\$\[\e[m\] '; \
if [[ ! -e ~/.bashrc ]]; then touch ~/.bashrc; fi; \
if [[ ! -e ~/.bashrc_orig ]]; then cp ~/.bashrc ~/.bashrc_orig; fi; \
rm -f ~/.bashrc; cp ~/.bashrc_orig ~/.bashrc; \
echo \"alias ls='ls --color=always'\" >> ~/.bashrc; \
echo \"alias ll='ls --color=always -lah'\" >> ~/.bashrc; \
bash"
