#!/usr/bin/env ruby

if __FILE__ == $PROGRAM_NAME
  require 'json'
  require 'securerandom'

  # Make sure that the docker VM is running
  docker_env = `docker-machine env default 2>&1`
  unless docker_env.strip == 'Error checking TLS connection: Host is not running'
    docker_names = `eval $(#{ docker_env }) && docker ps --format '{{.Names}}' 2>/dev/null`
  end

  docker_json = File.expand_path('~/Library/Application Support/iTerm2/DynamicProfiles/docker.json')
  if docker_names.nil? || docker_names.empty?
    puts "No active docker containers. Removing docker profiles."
    `rm '#{ docker_json }'`
  else
    puts "Running Docker containers found. Adding docker profiles."
    profiles = []
    docker_names.each_line do |name|
      name.strip!
      profile = {
        Name: name,
        Guid: SecureRandom.uuid,
        'Dynamic Profile Parent Name': 'Docker',
        'Initial Text': "docker-exec #{ name }"
      }

      profiles << profile
    end

    File.write(docker_json, {Profiles: profiles}.to_json)
  end
end
