#!/usr/bin/env ruby

if __FILE__ == $PROGRAM_NAME
  require 'json'
  require 'securerandom'

  #
  # Make sure that a docker VM is running
  # Unfortunately, if there are errors with a docker machine, then the error will still spill out
  # Remove it using grep
  #
  docker_env = `docker-machine ls --filter "state=Running" --format '{{.Active}}\t{{.Name}}\t{{.State}}' | grep Running`.strip
  unless docker_env.empty?
    if docker_env.lines.count > 1
      puts "More than 1 docker environment found. Defaulting to active (or first) environment"
    end

    env = nil
    docker_env.each_line do |line|
      active, name = line.split("\t")
      if env.nil? || active == '*'
        env = name
      end
    end

    cmd = "eval $(docker-machine env #{ env }) && docker ps --format '{{.Names}}\t{{.ID}}'"
    docker_ps = `#{ cmd }`
  end

  docker_json = File.expand_path('~/Library/Application Support/iTerm2/DynamicProfiles/docker.json')
  if docker_ps.nil? || docker_ps.empty?
    if File.exists?(docker_json)
      puts "No active docker containers. Removing docker profiles."
      `rm '#{ docker_json }'`
    end
  else
    puts "Adding new docker profiles." unless File.exists?(docker_json)
    profiles = []
    docker_ps.each_line do |line|
      name, host = line.split(/\t/)
      name.strip!
      host.strip!
      profile = {
        Name: name,
        Guid: SecureRandom.uuid,
        'Dynamic Profile Parent Name': 'Docker',
        'Initial Text': "docker-exec #{ name }",
        'Bound Hosts': [host]
      }

      profiles << profile
    end

    File.write(docker_json, {Profiles: profiles}.to_json)
  end
end
